/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/*
 * ---------------------------------------------------------------
 * ## THIS FILE WAS GENERATED VIA SWAGGER-TYPESCRIPT-API        ##
 * ##                                                           ##
 * ## AUTHOR: acacode                                           ##
 * ## SOURCE: https://github.com/acacode/swagger-typescript-api ##
 * ---------------------------------------------------------------
 */

import {
  Pageable,
  TimetableBasicLessonDto,
  TimetableBasicLessonsBatchDto,
  TimetableBasicLessonsDeleteBatchDto,
  TimetableBasicTemplateLessonsInitializeDto,
  TimetableBasicTemplateNameUpdateDto,
  TimetableConcurrentConfCreateDto,
  TimetableConcurrentConfDeleteDto,
  TimetableConcurrentConfUpdateRequestDto,
  TimetableConcurrentCourseFixRequestDto,
  TimetableConcurrentCourseUpdateDto,
  TimetableConfigRequestDto,
  TimetableConsecutiveConfCreateDto,
  TimetableConsecutiveConfDeleteDto,
  TimetableConsecutiveConfUpdateDto,
  TimetableCourseBaseBatchRequestDto,
  TimetableCourseBaseDeleteDto,
  TimetableCourseBaseRequestDto,
  TimetableCourseBaseSortDto,
  TimetableCourseDeleteDto,
  TimetableCourseRequestDto,
  TimetableCourseSortDto,
  TimetableElementRequestDto,
  TimetableFinishStatusDto,
  TimetableFixedConfRequestDto,
  TimetableGradeUpdateDto,
  TimetableIndexRequestDto,
  TimetableLessonAdditionRequestDto,
  TimetableLessonAdjustmentRequestDto,
  TimetableLessonChangeRequestDto,
  TimetableLessonChangeStatusAndReasonDto,
  TimetableLessonChangeUpdateDto,
  TimetableLessonCombinationRequestDto,
  TimetableLessonConfCreateDto,
  TimetableLessonConfDeleteRequestDto,
  TimetableLessonConfSpecialtyRoomUpdateDto,
  TimetableLessonConfSwapRequestDto,
  TimetableLessonConfTossRequestDto,
  TimetableLessonCreateDeleteRequestDto,
  TimetableLessonExchangeInfoDto,
  TimetableLessonHistoryRequestDto,
  TimetableLessonMultipleRequestDto,
  TimetableLessonReplacementRequestDto,
  TimetableLessonSwapRequestDto,
  TimetableLessonTossRequestDto,
  TimetableSimilarCourseConfCreateDto,
  TimetableSimilarCourseConfDeleteDto,
  TimetableSimilarCourseConfUpdateDto,
  TimetableSimilarCourseUpdateDto,
  TimetableSpecialtyRoomConfCreateDto,
  TimetableSpecialtyRoomConfDeleteDto,
  TimetableSpecialtyRoomConfUpdateDto,
  TimetableSpecialtyRoomCreateDto,
  TimetableSpecialtyRoomMaxClassUpdateDto,
  TimetableSpecialtyRoomNameUpdateDto,
  TimetableTeacherCreateDto,
  TimetableTeacherDeleteDto,
  TimetableTeacherUpdateDto,
  TimetableTeacherUpdateFreePeriodsRequestDto,
  TimetableTemplateAutoGenerateDto,
  TimetableUpdateDailyScheduleDto,
  TimetableUpdateDailyTimeScheduleDto,
  TimetableUpdateStatusDto,
  TimetableUploadLessonConfDto,
} from "./data-contracts";
import { ContentType, HttpClient, RequestParams } from "./http-client";

export class Timetables<
  SecurityDataType = unknown,
> extends HttpClient<SecurityDataType> {
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name GetTimetableTimetablesTimetableId
   * @request GET:/timetables/{timetableId}
   * @secure
   */
  getTimetableTimetablesTimetableId = (
    timetableId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}`,
      method: "GET",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name CreateTimetableConfigTimetablesTimetableId
   * @request POST:/timetables/{timetableId}
   * @secure
   */
  createTimetableConfigTimetablesTimetableId = (
    timetableId: string,
    data: TimetableConfigRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name DeleteTimetableTimetablesTimetableId
   * @request DELETE:/timetables/{timetableId}
   * @secure
   */
  deleteTimetableTimetablesTimetableId = (
    timetableId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}`,
      method: "DELETE",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name UpdateTimetableConfigTimetablesTimetableId
   * @request PATCH:/timetables/{timetableId}
   * @secure
   */
  updateTimetableConfigTimetablesTimetableId = (
    timetableId: string,
    data: TimetableConfigRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 99. 시수표 업로드
   * @name UploadTimetableLessonConfsLessonconfs
   * @request POST:/timetables/{timetableId}/upload/lesson-confs
   * @secure
   */
  uploadTimetableLessonConfsLessonconfs = (
    timetableId: string,
    data: TimetableUploadLessonConfDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/upload/lesson-confs`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 02. 시간표 교사 정보
   * @name GetTimetableTeachersTeachers
   * @request GET:/timetables/{timetableId}/teachers
   * @secure
   */
  getTimetableTeachersTeachers = (
    timetableId: string,
    query?: {
      /** @format uuid */
      templateId?: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/teachers`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 02. 시간표 교사 정보
   * @name AddTeachersTeachers
   * @request POST:/timetables/{timetableId}/teachers
   * @secure
   */
  addTeachersTeachers = (
    timetableId: string,
    data: TimetableTeacherCreateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/teachers`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 02. 시간표 교사 정보
   * @name DeleteTeacherTeachers
   * @request DELETE:/timetables/{timetableId}/teachers
   * @secure
   */
  deleteTeacherTeachers = (
    timetableId: string,
    data: TimetableTeacherDeleteDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/teachers`,
      method: "DELETE",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 02. 시간표 교사 정보
   * @name AddCourseToTeacherCoursesCourseId
   * @request POST:/timetables/{timetableId}/teachers/{teacherId}/courses/{courseId}
   * @secure
   */
  addCourseToTeacherCoursesCourseId = (
    timetableId: string,
    teacherId: string,
    courseId: string,
    query: {
      /** @format uuid */
      templateId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/teachers/${teacherId}/courses/${courseId}`,
      method: "POST",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 02. 시간표 교사 정보
   * @name RemoveCourseFromTeacherCoursesCourseId
   * @request DELETE:/timetables/{timetableId}/teachers/{teacherId}/courses/{courseId}
   * @secure
   */
  removeCourseFromTeacherCoursesCourseId = (
    timetableId: string,
    teacherId: string,
    courseId: string,
    query: {
      /** @format uuid */
      templateId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/teachers/${teacherId}/courses/${courseId}`,
      method: "DELETE",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 02. 시간표 교사 정보
   * @name AddCourseBaseToTeacherCoursebaseCourseBaseId
   * @request POST:/timetables/{timetableId}/teachers/{teacherId}/course-base/{courseBaseId}
   * @secure
   */
  addCourseBaseToTeacherCoursebaseCourseBaseId = (
    timetableId: string,
    teacherId: string,
    courseBaseId: string,
    query: {
      /** @format uuid */
      templateId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/teachers/${teacherId}/course-base/${courseBaseId}`,
      method: "POST",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 02. 시간표 교사 정보
   * @name RemoveCourseBaseFromTeacherCoursebaseCourseBaseId
   * @request DELETE:/timetables/{timetableId}/teachers/{teacherId}/course-base/{courseBaseId}
   * @secure
   */
  removeCourseBaseFromTeacherCoursebaseCourseBaseId = (
    timetableId: string,
    teacherId: string,
    courseBaseId: string,
    query: {
      /** @format uuid */
      templateId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/teachers/${teacherId}/course-base/${courseBaseId}`,
      method: "DELETE",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-specialty-room-controller
   * @name GetTimetableSpecialtyRoomsSpecialtyrooms
   * @request GET:/timetables/{timetableId}/specialty-rooms
   * @secure
   */
  getTimetableSpecialtyRoomsSpecialtyrooms = (
    timetableId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/specialty-rooms`,
      method: "GET",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-specialty-room-controller
   * @name CreateSpecialtyRoomSpecialtyrooms
   * @request POST:/timetables/{timetableId}/specialty-rooms
   * @secure
   */
  createSpecialtyRoomSpecialtyrooms = (
    timetableId: string,
    data: TimetableSpecialtyRoomCreateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/specialty-rooms`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-specialty-room-conf-controller
   * @name GetTimetableSpecialtyRoomConfsSpecialtyroomconfs
   * @request GET:/timetables/{timetableId}/specialty-room-confs
   * @secure
   */
  getTimetableSpecialtyRoomConfsSpecialtyroomconfs = (
    timetableId: string,
    query: {
      /** @format uuid */
      templateId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/specialty-room-confs`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-specialty-room-conf-controller
   * @name CreateSpecialtyRoomConfsSpecialtyroomconfs
   * @request POST:/timetables/{timetableId}/specialty-room-confs
   * @secure
   */
  createSpecialtyRoomConfsSpecialtyroomconfs = (
    timetableId: string,
    data: TimetableSpecialtyRoomConfCreateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/specialty-room-confs`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-specialty-room-conf-controller
   * @name DeleteSpecialtyRoomConfSpecialtyroomconfs
   * @request DELETE:/timetables/{timetableId}/specialty-room-confs
   * @secure
   */
  deleteSpecialtyRoomConfSpecialtyroomconfs = (
    timetableId: string,
    data: TimetableSpecialtyRoomConfDeleteDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/specialty-room-confs`,
      method: "DELETE",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-similar-course-conf-controller
   * @name GetSimilarCourseConfsSimilarcourseconfs
   * @request GET:/timetables/{timetableId}/similar-course-confs
   * @secure
   */
  getSimilarCourseConfsSimilarcourseconfs = (
    timetableId: string,
    query: {
      /** @format uuid */
      templateId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/similar-course-confs`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-similar-course-conf-controller
   * @name CreateSimilarCourseConfSimilarcourseconfs
   * @request POST:/timetables/{timetableId}/similar-course-confs
   * @secure
   */
  createSimilarCourseConfSimilarcourseconfs = (
    timetableId: string,
    data: TimetableSimilarCourseConfCreateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/similar-course-confs`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-similar-course-conf-controller
   * @name DeleteSimilarCourseConfSimilarcourseconfs
   * @request DELETE:/timetables/{timetableId}/similar-course-confs
   * @secure
   */
  deleteSimilarCourseConfSimilarcourseconfs = (
    timetableId: string,
    data: TimetableSimilarCourseConfDeleteDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/similar-course-confs`,
      method: "DELETE",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 03. 시간표 기준 과목 정보
   * @name AttachSimilarCourseCoursebases
   * @request POST:/timetables/{timetableId}/similar-course-confs/{similarCourseConfId}/course-bases
   * @secure
   */
  attachSimilarCourseCoursebases = (
    timetableId: string,
    similarCourseConfId: string,
    data: TimetableSimilarCourseUpdateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/similar-course-confs/${similarCourseConfId}/course-bases`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-lesson-history-controller
   * @name GetTimetableLessonHistoryLessonhistories
   * @request GET:/timetables/{timetableId}/lesson-histories
   * @secure
   */
  getTimetableLessonHistoryLessonhistories = (
    timetableId: string,
    query: {
      /** @format uuid */
      templateId: string;
      pageable: Pageable;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-histories`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-lesson-history-controller
   * @name SaveTimetableCurrentLessonHistoryLessonhistories
   * @request POST:/timetables/{timetableId}/lesson-histories
   * @secure
   */
  saveTimetableCurrentLessonHistoryLessonhistories = (
    timetableId: string,
    data: TimetableLessonHistoryRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-histories`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-lesson-history-controller
   * @name RestoreTimetableLessonHistoryRestore
   * @request POST:/timetables/{timetableId}/lesson-histories/{lessonHistoryId}/restore
   * @secure
   */
  restoreTimetableLessonHistoryRestore = (
    timetableId: string,
    lessonHistoryId: string,
    query: {
      /** @format uuid */
      templateId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-histories/${lessonHistoryId}/restore`,
      method: "POST",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 04. 시수표 정보 관리
   * @name GetTimetableLessonConfsLessonconfs
   * @request GET:/timetables/{timetableId}/lesson-confs
   * @secure
   */
  getTimetableLessonConfsLessonconfs = (
    timetableId: string,
    query: {
      /** @format uuid */
      templateId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-confs`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 04. 시수표 정보 관리
   * @name CreateLessonConfLessonconfs
   * @request POST:/timetables/{timetableId}/lesson-confs
   * @secure
   */
  createLessonConfLessonconfs = (
    timetableId: string,
    data: TimetableLessonConfCreateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-confs`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 04. 시수표 정보 관리
   * @name DeleteLessonConfsLessonconfs
   * @request DELETE:/timetables/{timetableId}/lesson-confs
   * @secure
   */
  deleteLessonConfsLessonconfs = (
    timetableId: string,
    data: TimetableLessonConfDeleteRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-confs`,
      method: "DELETE",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * @description 수업 변경과 함께 승인 진행 가능. reqeustDto의 status에 따라 다르게 처리.
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name RequestToChangeForReplacementReplacements
   * @summary (관리자용) 수업 변경 요청
   * @request POST:/timetables/{timetableId}/lesson-changes/replacements
   * @secure
   */
  requestToChangeForReplacementReplacements = (
    timetableId: string,
    data: TimetableLessonReplacementRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/replacements`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * @description 권한과 상관없이 항상 PENDING 상태로 처리.
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name RequestReplacementForTeacherReplacementrequests
   * @summary (교사용) 수업 변경 요청
   * @request POST:/timetables/{timetableId}/lesson-changes/replacement-requests
   * @secure
   */
  requestReplacementForTeacherReplacementrequests = (
    timetableId: string,
    data: TimetableLessonReplacementRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/replacement-requests`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name RequestToChangeForRemovalRemovals
   * @request POST:/timetables/{timetableId}/lesson-changes/removals
   * @secure
   */
  requestToChangeForRemovalRemovals = (
    timetableId: string,
    data: TimetableLessonChangeRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/removals`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name GetTeacherOptionsForMultipleMultipleteachers
   * @request GET:/timetables/{timetableId}/lesson-changes/multiple-teachers
   * @secure
   */
  getTeacherOptionsForMultipleMultipleteachers = (
    timetableId: string,
    query: {
      /** @format int32 */
      lessonDate: number;
      /** @format int32 */
      period: number;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/multiple-teachers`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name RequestToChangeForMultipleMultipleteachers
   * @request POST:/timetables/{timetableId}/lesson-changes/multiple-teachers
   * @secure
   */
  requestToChangeForMultipleMultipleteachers = (
    timetableId: string,
    data: TimetableLessonMultipleRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/multiple-teachers`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * @description 수업 교체와 함께 승인 진행 가능. reqeustDto의 status에 따라 다르게 처리.
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name ExchangeLessonsExchanges
   * @summary (관리자용) 수업 교체 요청
   * @request POST:/timetables/{timetableId}/lesson-changes/exchanges
   * @secure
   */
  exchangeLessonsExchanges = (
    timetableId: string,
    data: TimetableLessonExchangeInfoDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/exchanges`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * @description 권한과 상관없이 항상 PENDING 상태로 처리.
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name RequestExchangeForTeacherExchangerequests
   * @summary (교사용) 수업 교체 요청
   * @request POST:/timetables/{timetableId}/lesson-changes/exchange-requests
   * @secure
   */
  requestExchangeForTeacherExchangerequests = (
    timetableId: string,
    data: TimetableLessonExchangeInfoDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/exchange-requests`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name RequestToChangeForEventEvents
   * @request POST:/timetables/{timetableId}/lesson-changes/events
   * @secure
   */
  requestToChangeForEventEvents = (
    timetableId: string,
    data: TimetableLessonChangeRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/events`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name RequestToChangeForDuplicationDuplications
   * @request POST:/timetables/{timetableId}/lesson-changes/duplications
   * @secure
   */
  requestToChangeForDuplicationDuplications = (
    timetableId: string,
    data: TimetableLessonChangeRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/duplications`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name GetTeacherOptionsForCombinationCombinations
   * @request GET:/timetables/{timetableId}/lesson-changes/combinations
   * @secure
   */
  getTeacherOptionsForCombinationCombinations = (
    timetableId: string,
    query: {
      /** @format uuid */
      dailyLessonId: string;
      /** @format int32 */
      lessonDate: number;
      /** @format int32 */
      period: number;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/combinations`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name RequestToChangeForCombinationCombinations
   * @request POST:/timetables/{timetableId}/lesson-changes/combinations
   * @secure
   */
  requestToChangeForCombinationCombinations = (
    timetableId: string,
    data: TimetableLessonCombinationRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/combinations`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * @description 수업 결/보강과 함께 승인 진행 가능. reqeustDto의 status에 따라 다르게 처리.
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name RequestToChangeForAdjustmentAdjustments
   * @summary (관리자용) 수업 결/보강 요청
   * @request POST:/timetables/{timetableId}/lesson-changes/adjustments
   * @secure
   */
  requestToChangeForAdjustmentAdjustments = (
    timetableId: string,
    data: TimetableLessonAdjustmentRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/adjustments`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * @description 권한과 상관없이 항상 PENDING 상태로 처리.
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name RequestAdjustmentForTeacherAdjustmentrequests
   * @summary (교사용) 수업 결/보강 요청
   * @request POST:/timetables/{timetableId}/lesson-changes/adjustment-requests
   * @secure
   */
  requestAdjustmentForTeacherAdjustmentrequests = (
    timetableId: string,
    data: TimetableLessonAdjustmentRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/adjustment-requests`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * @description 수업 추가와 함께 승인 진행 가능. reqeustDto의 status에 따라 다르게 처리.
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name RequestToCreateForAdditionAdditions
   * @summary (관리자용) 수업 추가 요청
   * @request POST:/timetables/{timetableId}/lesson-changes/additions
   * @secure
   */
  requestToCreateForAdditionAdditions = (
    timetableId: string,
    data: TimetableLessonAdditionRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/additions`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * @description 권한과 상관없이 항상 PENDING 상태로 처리.
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name RequestAdditionForTeacherAdditionrequests
   * @summary (교사용) 수업 추가 요청
   * @request POST:/timetables/{timetableId}/lesson-changes/addition-requests
   * @secure
   */
  requestAdditionForTeacherAdditionrequests = (
    timetableId: string,
    data: TimetableLessonAdditionRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/addition-requests`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-fixed-conf-controller
   * @name GetTimetableFixedConfsFixedconfs
   * @request GET:/timetables/{timetableId}/fixed-confs
   * @secure
   */
  getTimetableFixedConfsFixedconfs = (
    timetableId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/fixed-confs`,
      method: "GET",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-fixed-conf-controller
   * @name CreateFixedConfsFixedconfs
   * @request POST:/timetables/{timetableId}/fixed-confs
   * @secure
   */
  createFixedConfsFixedconfs = (
    timetableId: string,
    data: TimetableFixedConfRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/fixed-confs`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-fixed-conf-controller
   * @name RearrangeFixedConfsConcurrentcourse
   * @request POST:/timetables/{timetableId}/fixed-confs/concurrent-course
   * @secure
   */
  rearrangeFixedConfsConcurrentcourse = (
    timetableId: string,
    data: TimetableConcurrentCourseFixRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/fixed-confs/concurrent-course`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name CreateFirstTemplateFirsttemplate
   * @request POST:/timetables/{timetableId}/first-template
   * @secure
   */
  createFirstTemplateFirsttemplate = (
    timetableId: string,
    data: TimetableBasicTemplateNameUpdateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/first-template`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 05. 시간표 과목 관리
   * @name GetTimetableCoursesCourses
   * @request GET:/timetables/{timetableId}/courses
   * @secure
   */
  getTimetableCoursesCourses = (
    timetableId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/courses`,
      method: "GET",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 05. 시간표 과목 관리
   * @name SaveCourseCourses
   * @request POST:/timetables/{timetableId}/courses
   * @secure
   */
  saveCourseCourses = (
    timetableId: string,
    data: TimetableCourseRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/courses`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 05. 시간표 과목 관리
   * @name DeleteCourseCourses
   * @request DELETE:/timetables/{timetableId}/courses
   * @secure
   */
  deleteCourseCourses = (
    timetableId: string,
    data: TimetableCourseDeleteDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/courses`,
      method: "DELETE",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 05. 시간표 과목 관리
   * @name CreateUnifiedCourseUnifiedcourse
   * @request POST:/timetables/{timetableId}/courses/unified-course
   * @secure
   */
  createUnifiedCourseUnifiedcourse = (
    timetableId: string,
    data: TimetableCourseRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/courses/unified-course`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 03. 시간표 기준 과목 정보
   * @name GetTimetableCourseBasesCoursebases
   * @request GET:/timetables/{timetableId}/course-bases
   * @secure
   */
  getTimetableCourseBasesCoursebases = (
    timetableId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/course-bases`,
      method: "GET",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 03. 시간표 기준 과목 정보
   * @name SaveCourseBaseCoursebases
   * @request POST:/timetables/{timetableId}/course-bases
   * @secure
   */
  saveCourseBaseCoursebases = (
    timetableId: string,
    data: TimetableCourseBaseRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/course-bases`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 03. 시간표 기준 과목 정보
   * @name DeleteCourseBaseCoursebases
   * @request DELETE:/timetables/{timetableId}/course-bases
   * @secure
   */
  deleteCourseBaseCoursebases = (
    timetableId: string,
    data: TimetableCourseBaseDeleteDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/course-bases`,
      method: "DELETE",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 03. 시간표 기준 과목 정보
   * @name SaveCourseBaseBatchBatch
   * @request POST:/timetables/{timetableId}/course-bases/batch
   * @secure
   */
  saveCourseBaseBatchBatch = (
    timetableId: string,
    data: TimetableCourseBaseBatchRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/course-bases/batch`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-consecutive-conf-controller
   * @name GetConsecutiveConfListConsecutiveconfs
   * @request GET:/timetables/{timetableId}/consecutive-confs
   * @secure
   */
  getConsecutiveConfListConsecutiveconfs = (
    timetableId: string,
    query: {
      /** @format uuid */
      templateId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/consecutive-confs`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-consecutive-conf-controller
   * @name CreateConsecutiveConfsConsecutiveconfs
   * @request POST:/timetables/{timetableId}/consecutive-confs
   * @secure
   */
  createConsecutiveConfsConsecutiveconfs = (
    timetableId: string,
    data: TimetableConsecutiveConfCreateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/consecutive-confs`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-consecutive-conf-controller
   * @name DeleteConsecutiveConfsConsecutiveconfs
   * @request DELETE:/timetables/{timetableId}/consecutive-confs
   * @secure
   */
  deleteConsecutiveConfsConsecutiveconfs = (
    timetableId: string,
    data: TimetableConsecutiveConfDeleteDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/consecutive-confs`,
      method: "DELETE",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-concurrent-conf-controller
   * @name GetConcurrentConfListConcurrentconfs
   * @request GET:/timetables/{timetableId}/concurrent-confs
   * @secure
   */
  getConcurrentConfListConcurrentconfs = (
    timetableId: string,
    query: {
      /** @format uuid */
      templateId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/concurrent-confs`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-concurrent-conf-controller
   * @name CreateConcurrentCourseConcurrentconfs
   * @request POST:/timetables/{timetableId}/concurrent-confs
   * @secure
   */
  createConcurrentCourseConcurrentconfs = (
    timetableId: string,
    data: TimetableConcurrentConfCreateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/concurrent-confs`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-concurrent-conf-controller
   * @name DeleteConcurrentConfsConcurrentconfs
   * @request DELETE:/timetables/{timetableId}/concurrent-confs
   * @secure
   */
  deleteConcurrentConfsConcurrentconfs = (
    timetableId: string,
    data: TimetableConcurrentConfDeleteDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/concurrent-confs`,
      method: "DELETE",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-concurrent-conf-controller
   * @name AttachConcurrentCourseLessonconfs
   * @request POST:/timetables/{timetableId}/concurrent-confs/{concurrentConfId}/lesson-confs
   * @secure
   */
  attachConcurrentCourseLessonconfs = (
    timetableId: string,
    concurrentConfId: string,
    data: TimetableConcurrentCourseUpdateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/concurrent-confs/${concurrentConfId}/lesson-confs`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-concurrent-conf-controller
   * @name DetachConcurrentCourseLessonconfs
   * @request DELETE:/timetables/{timetableId}/concurrent-confs/{concurrentConfId}/lesson-confs
   * @secure
   */
  detachConcurrentCourseLessonconfs = (
    timetableId: string,
    concurrentConfId: string,
    data: TimetableConcurrentCourseUpdateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/concurrent-confs/${concurrentConfId}/lesson-confs`,
      method: "DELETE",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-basic-template-controller
   * @name DuplicateTimetableBasicTemplateDuplicate
   * @request POST:/timetables/{timetableId}/basic-templates/{templateId}/duplicate
   * @secure
   */
  duplicateTimetableBasicTemplateDuplicate = (
    timetableId: string,
    templateId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/basic-templates/${templateId}/duplicate`,
      method: "POST",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-basic-template-controller
   * @name SaveTimetableBasicTemplateLessonLesson
   * @request POST:/timetables/{timetableId}/basic-template/lesson
   * @secure
   */
  saveTimetableBasicTemplateLessonLesson = (
    timetableId: string,
    data: TimetableBasicLessonDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/basic-template/lesson`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-basic-template-controller
   * @name GetTimetableBasicTemplateLessonsLessons
   * @request GET:/timetables/{timetableId}/basic-template/lessons
   * @secure
   */
  getTimetableBasicTemplateLessonsLessons = (
    timetableId: string,
    query: {
      /** @format uuid */
      templateId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/basic-template/lessons`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-basic-template-controller
   * @name SaveTimetableBasicTemplateLessonsLessons
   * @request POST:/timetables/{timetableId}/basic-template/lessons
   * @secure
   */
  saveTimetableBasicTemplateLessonsLessons = (
    timetableId: string,
    data: TimetableBasicLessonsBatchDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/basic-template/lessons`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-basic-template-controller
   * @name DeleteTimetableBasicTemplateLessonsLessons
   * @request DELETE:/timetables/{timetableId}/basic-template/lessons
   * @secure
   */
  deleteTimetableBasicTemplateLessonsLessons = (
    timetableId: string,
    data: TimetableBasicLessonsDeleteBatchDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/basic-template/lessons`,
      method: "DELETE",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-basic-template-controller
   * @name TossTimetableBasicTemplateLessonsToss
   * @request POST:/timetables/{timetableId}/basic-template/lessons/toss
   * @secure
   */
  tossTimetableBasicTemplateLessonsToss = (
    timetableId: string,
    data: TimetableLessonTossRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/basic-template/lessons/toss`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-basic-template-controller
   * @name SwapTimetableBasicTemplateLessonsSwap
   * @request POST:/timetables/{timetableId}/basic-template/lessons/swap
   * @secure
   */
  swapTimetableBasicTemplateLessonsSwap = (
    timetableId: string,
    data: TimetableLessonSwapRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/basic-template/lessons/swap`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-basic-template-controller
   * @name UpdateTimetableBasicTemplateLessonsBatchupdate
   * @request POST:/timetables/{timetableId}/basic-template/lessons/batch-update
   * @secure
   */
  updateTimetableBasicTemplateLessonsBatchupdate = (
    timetableId: string,
    data: TimetableLessonCreateDeleteRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/basic-template/lessons/batch-update`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name CreateTimetableIndex
   * @request POST:/timetables/index
   * @secure
   */
  createTimetableIndex = (
    data: TimetableIndexRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/index`,
      method: "POST",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name UpdateTimetableNameTimetableName
   * @request PATCH:/timetables/{timetableId}/timetableName
   * @secure
   */
  updateTimetableNameTimetableName = (
    timetableId: string,
    data: TimetableElementRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/timetableName`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name UpdateTimetableMemoTimetableMemo
   * @request PATCH:/timetables/{timetableId}/timetableMemo
   * @secure
   */
  updateTimetableMemoTimetableMemo = (
    timetableId: string,
    data: TimetableElementRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/timetableMemo`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 02. 시간표 교사 정보
   * @name UpdateTeacherNameName
   * @request PATCH:/timetables/{timetableId}/teachers/{teacherId}/name
   * @secure
   */
  updateTeacherNameName = (
    timetableId: string,
    teacherId: string,
    data: TimetableTeacherUpdateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/teachers/${teacherId}/name`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 02. 시간표 교사 정보
   * @name DeleteManagingClassManager
   * @request DELETE:/timetables/{timetableId}/teachers/{teacherId}/manager
   * @secure
   */
  deleteManagingClassManager = (
    timetableId: string,
    teacherId: string,
    query: {
      /** @format uuid */
      templateId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/teachers/${teacherId}/manager`,
      method: "DELETE",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 02. 시간표 교사 정보
   * @name UpdateManagingClassManager
   * @request PATCH:/timetables/{timetableId}/teachers/{teacherId}/manager
   * @secure
   */
  updateManagingClassManager = (
    timetableId: string,
    teacherId: string,
    data: TimetableTeacherUpdateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/teachers/${teacherId}/manager`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 02. 시간표 교사 정보
   * @name UpdateFreePeriodsFreeperiods
   * @request PATCH:/timetables/{timetableId}/teachers/{teacherId}/free-periods
   * @secure
   */
  updateFreePeriodsFreeperiods = (
    timetableId: string,
    teacherId: string,
    data: TimetableTeacherUpdateFreePeriodsRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/teachers/${teacherId}/free-periods`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name PatchTimetableStatusStatusStatus
   * @request PATCH:/timetables/{timetableId}/status/{status}
   * @secure
   */
  patchTimetableStatusStatusStatus = (
    timetableId: string,
    status:
      | "INIT"
      | "EDIT"
      | "WEEKLY_PERIOD"
      | "COURSE_BASE"
      | "TEACHER"
      | "LESSON_CONFIG"
      | "ADDITIONAL_WORK"
      | "GENERATE"
      | "FINISH",
    query?: {
      /** @format uuid */
      templateId?: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/status/${status}`,
      method: "PATCH",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name PatchStatusGenerateGenerate
   * @request PATCH:/timetables/{timetableId}/status/generate
   * @deprecated
   * @secure
   */
  patchStatusGenerateGenerate = (
    timetableId: string,
    data: TimetableUpdateStatusDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/status/generate`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name PatchStatusFinishFinish
   * @request PATCH:/timetables/{timetableId}/status/finish
   * @secure
   */
  patchStatusFinishFinish = (
    timetableId: string,
    data: TimetableFinishStatusDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/status/finish`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name PatchStatusEditEdit
   * @request PATCH:/timetables/{timetableId}/status/edit
   * @secure
   */
  patchStatusEditEdit = (timetableId: string, params: RequestParams = {}) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/status/edit`,
      method: "PATCH",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-specialty-room-controller
   * @name UpdateSpecialtyRoomNameRoomname
   * @request PATCH:/timetables/{timetableId}/specialty-rooms/{specialtyRoomId}/room-name
   * @secure
   */
  updateSpecialtyRoomNameRoomname = (
    timetableId: string,
    specialtyRoomId: string,
    data: TimetableSpecialtyRoomNameUpdateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/specialty-rooms/${specialtyRoomId}/room-name`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-specialty-room-controller
   * @name UpdateMaxClassOnSpecialtyRoomMaxclass
   * @request PATCH:/timetables/{timetableId}/specialty-rooms/{specialtyRoomId}/max-class
   * @secure
   */
  updateMaxClassOnSpecialtyRoomMaxclass = (
    timetableId: string,
    specialtyRoomId: string,
    data: TimetableSpecialtyRoomMaxClassUpdateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/specialty-rooms/${specialtyRoomId}/max-class`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-specialty-room-conf-controller
   * @name UpdateSpecialtyRoomConfSpecialtyroomconfsSpecialtyRoomConfId
   * @request PATCH:/timetables/{timetableId}/specialty-room-confs/{specialtyRoomConfId}
   * @secure
   */
  updateSpecialtyRoomConfSpecialtyroomconfsSpecialtyRoomConfId = (
    timetableId: string,
    specialtyRoomConfId: string,
    data: TimetableSpecialtyRoomConfUpdateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/specialty-room-confs/${specialtyRoomConfId}`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 04. 시수표 정보 관리
   * @name AttachSpecialtyRoomConfOnLessonConfLessonconfs
   * @request PATCH:/timetables/{timetableId}/specialty-room-confs/{specialtyRoomConfId}/lesson-confs
   * @secure
   */
  attachSpecialtyRoomConfOnLessonConfLessonconfs = (
    timetableId: string,
    specialtyRoomConfId: string,
    data: TimetableLessonConfSpecialtyRoomUpdateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/specialty-room-confs/${specialtyRoomConfId}/lesson-confs`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 04. 시수표 정보 관리
   * @name DetachSpecialtyRoomConfOnLessonConfLessonconfsLessonConfId
   * @request PATCH:/timetables/{timetableId}/specialty-room-confs/{specialtyRoomConfId}/lesson-confs/{lessonConfId}
   * @secure
   */
  detachSpecialtyRoomConfOnLessonConfLessonconfsLessonConfId = (
    timetableId: string,
    specialtyRoomConfId: string,
    lessonConfId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/specialty-room-confs/${specialtyRoomConfId}/lesson-confs/${lessonConfId}`,
      method: "PATCH",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-similar-course-conf-controller
   * @name UpdateSimilarCourseConfSimilarcourseconfsSimilarCourseConfId
   * @request PATCH:/timetables/{timetableId}/similar-course-confs/{similarCourseConfId}
   * @secure
   */
  updateSimilarCourseConfSimilarcourseconfsSimilarCourseConfId = (
    timetableId: string,
    similarCourseConfId: string,
    data: TimetableSimilarCourseConfUpdateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/similar-course-confs/${similarCourseConfId}`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-lesson-history-controller
   * @name UpdateTimetableLessonHistoryMemoMemo
   * @request PATCH:/timetables/{timetableId}/lesson-histories/{lessonHistoryId}/memo
   * @secure
   */
  updateTimetableLessonHistoryMemoMemo = (
    timetableId: string,
    lessonHistoryId: string,
    data: TimetableLessonHistoryRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-histories/${lessonHistoryId}/memo`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 04. 시수표 정보 관리
   * @name TossLessonConfToss
   * @request PATCH:/timetables/{timetableId}/lesson-confs/toss
   * @secure
   */
  tossLessonConfToss = (
    timetableId: string,
    data: TimetableLessonConfTossRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-confs/toss`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 04. 시수표 정보 관리
   * @name SwapLessonConfsSwap
   * @request PATCH:/timetables/{timetableId}/lesson-confs/swap
   * @secure
   */
  swapLessonConfsSwap = (
    timetableId: string,
    data: TimetableLessonConfSwapRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-confs/swap`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name GetLessonChangeSimpleLessonchangesLessonChangeId
   * @request GET:/timetables/{timetableId}/lesson-changes/{lessonChangeId}
   * @secure
   */
  getLessonChangeSimpleLessonchangesLessonChangeId = (
    timetableId: string,
    lessonChangeId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/${lessonChangeId}`,
      method: "GET",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name RequestToPatchLessonChangeLessonchangesLessonChangeId
   * @request PATCH:/timetables/{timetableId}/lesson-changes/{lessonChangeId}
   * @secure
   */
  requestToPatchLessonChangeLessonchangesLessonChangeId = (
    timetableId: string,
    lessonChangeId: string,
    data: TimetableLessonChangeUpdateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/${lessonChangeId}`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name RequestToPatchLessonChangeStatusAndReasonStatusandreason
   * @request PATCH:/timetables/{timetableId}/lesson-changes/{lessonChangeId}/status-and-reason
   * @secure
   */
  requestToPatchLessonChangeStatusAndReasonStatusandreason = (
    timetableId: string,
    lessonChangeId: string,
    data: TimetableLessonChangeStatusAndReasonDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/${lessonChangeId}/status-and-reason`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name RequestToRecoverLessonChangeRecovery
   * @request PATCH:/timetables/{timetableId}/lesson-changes/{lessonChangeId}/recovery
   * @secure
   */
  requestToRecoverLessonChangeRecovery = (
    timetableId: string,
    lessonChangeId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/${lessonChangeId}/recovery`,
      method: "PATCH",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name UpdateTimetableIndex
   * @request PATCH:/timetables/{timetableId}/index
   * @secure
   */
  updateTimetableIndex = (
    timetableId: string,
    data: TimetableIndexRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/index`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-grade-controller
   * @name UpdateTimetableGradeBeforeLunchPeriodLunchtime
   * @request PATCH:/timetables/{timetableId}/grade/{grade}/lunch-time
   * @secure
   */
  updateTimetableGradeBeforeLunchPeriodLunchtime = (
    timetableId: string,
    grade: number,
    data: TimetableGradeUpdateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/grade/${grade}/lunch-time`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-grade-controller
   * @name UpdateTimetableGradeFreePeriodsFreeperiods
   * @request PATCH:/timetables/{timetableId}/grade/{grade}/free-periods
   * @secure
   */
  updateTimetableGradeFreePeriodsFreeperiods = (
    timetableId: string,
    grade: number,
    data: TimetableGradeUpdateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/grade/${grade}/free-periods`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name UpdateDailyTimeScheduleDailytimeschedule
   * @request PATCH:/timetables/{timetableId}/daily-time-schedule
   * @secure
   */
  updateDailyTimeScheduleDailytimeschedule = (
    timetableId: string,
    data: TimetableUpdateDailyTimeScheduleDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/daily-time-schedule`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name UpdateDailyScheduleDailyschedule
   * @request PATCH:/timetables/{timetableId}/daily-schedule
   * @secure
   */
  updateDailyScheduleDailyschedule = (
    timetableId: string,
    data: TimetableUpdateDailyScheduleDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/daily-schedule`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 05. 시간표 과목 관리
   * @name UpdateCourseCoursesCourseId
   * @request PATCH:/timetables/{timetableId}/courses/{courseId}
   * @secure
   */
  updateCourseCoursesCourseId = (
    timetableId: string,
    courseId: string,
    data: TimetableCourseRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/courses/${courseId}`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 05. 시간표 과목 관리
   * @name ChangeSequenceSequence
   * @request PATCH:/timetables/{timetableId}/courses/{courseId}/sequence
   * @secure
   */
  changeSequenceSequence = (
    timetableId: string,
    courseId: string,
    data: TimetableCourseSortDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/courses/${courseId}/sequence`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 03. 시간표 기준 과목 정보
   * @name UpdateCourseBaseCoursebasesCourseBaseId
   * @request PATCH:/timetables/{timetableId}/course-bases/{courseBaseId}
   * @secure
   */
  updateCourseBaseCoursebasesCourseBaseId = (
    timetableId: string,
    courseBaseId: string,
    data: TimetableCourseBaseRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/course-bases/${courseBaseId}`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 03. 시간표 기준 과목 정보
   * @name ChangeCourseBaseSequenceSequence
   * @request PATCH:/timetables/{timetableId}/course-bases/{courseBaseId}/sequence
   * @secure
   */
  changeCourseBaseSequenceSequence = (
    timetableId: string,
    courseBaseId: string,
    data: TimetableCourseBaseSortDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/course-bases/${courseBaseId}/sequence`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-consecutive-conf-controller
   * @name UpdateConsecutiveConfConsecutiveconfsConsecutiveConfId
   * @request PATCH:/timetables/{timetableId}/consecutive-confs/{consecutiveConfId}
   * @secure
   */
  updateConsecutiveConfConsecutiveconfsConsecutiveConfId = (
    timetableId: string,
    consecutiveConfId: string,
    data: TimetableConsecutiveConfUpdateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/consecutive-confs/${consecutiveConfId}`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-concurrent-conf-controller
   * @name UpdateConcurrentConfConcurrentconfsConcurrentConfId
   * @request PATCH:/timetables/{timetableId}/concurrent-confs/{concurrentConfId}
   * @secure
   */
  updateConcurrentConfConcurrentconfsConcurrentConfId = (
    timetableId: string,
    concurrentConfId: string,
    data: TimetableConcurrentConfUpdateRequestDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/concurrent-confs/${concurrentConfId}`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-basic-template-controller
   * @name UpdateTimetableBasicTemplateNameName
   * @request PATCH:/timetables/{timetableId}/basic-templates/{templateId}/name
   * @secure
   */
  updateTimetableBasicTemplateNameName = (
    timetableId: string,
    templateId: string,
    data: TimetableBasicTemplateNameUpdateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/basic-templates/${templateId}/name`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-basic-template-controller
   * @name InitializeTimetableBasicTemplateLessonsInitialize
   * @request PATCH:/timetables/{timetableId}/basic-template/lessons/initialize
   * @secure
   */
  initializeTimetableBasicTemplateLessonsInitialize = (
    timetableId: string,
    data: TimetableBasicTemplateLessonsInitializeDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/basic-template/lessons/initialize`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-basic-template-controller
   * @name GetTimetableBasicTemplateAutoGenerateCountAutogeneratecount
   * @request GET:/timetables/{timetableId}/basic-template/auto-generate-count
   * @secure
   */
  getTimetableBasicTemplateAutoGenerateCountAutogeneratecount = (
    timetableId: string,
    query: {
      /** @format uuid */
      templateId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/basic-template/auto-generate-count`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-basic-template-controller
   * @name UpdateTimetableBasicTemplateAutoGenerateCountAutogeneratecount
   * @request PATCH:/timetables/{timetableId}/basic-template/auto-generate-count
   * @secure
   */
  updateTimetableBasicTemplateAutoGenerateCountAutogeneratecount = (
    timetableId: string,
    data: TimetableTemplateAutoGenerateDto,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/basic-template/auto-generate-count`,
      method: "PATCH",
      body: data,
      secure: true,
      type: ContentType.Json,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name GetTimetableListTimetables
   * @request GET:/timetables
   * @secure
   */
  getTimetableListTimetables = (
    query: {
      /** @format uuid */
      schoolId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name GetDailyTimetableOverviewTimetableoverview
   * @request GET:/timetables/{timetableId}/timetable-overview
   * @secure
   */
  getDailyTimetableOverviewTimetableoverview = (
    timetableId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/timetable-overview`,
      method: "GET",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 02. 시간표 교사 정보
   * @name GetTeacherCourseConfsAllByTimetableIdTeachercourseconfs
   * @request GET:/timetables/{timetableId}/teacher-course-confs
   * @secure
   */
  getTeacherCourseConfsAllByTimetableIdTeachercourseconfs = (
    timetableId: string,
    query?: {
      /** @format uuid */
      templateId?: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/teacher-course-confs`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 02. 시간표 교사 정보
   * @name GetTeacherCourseBaseConfsAllByTimetableIdTeachercoursebaseconfs
   * @request GET:/timetables/{timetableId}/teacher-course-base-confs
   * @secure
   */
  getTeacherCourseBaseConfsAllByTimetableIdTeachercoursebaseconfs = (
    timetableId: string,
    query?: {
      /** @format uuid */
      templateId?: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/teacher-course-base-confs`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-similar-course-conf-controller
   * @name GetSimilarCoursesSimilarcourses
   * @request GET:/timetables/{timetableId}/similar-courses
   * @secure
   */
  getSimilarCoursesSimilarcourses = (
    timetableId: string,
    query: {
      /** @format uuid */
      templateId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/similar-courses`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name GetTimetableProgressInfoProgressinfo
   * @request GET:/timetables/{timetableId}/progress-info
   * @secure
   */
  getTimetableProgressInfoProgressinfo = (
    timetableId: string,
    query?: {
      /** @format uuid */
      templateId?: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/progress-info`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 04. 시수표 정보 관리
   * @name SearchLessonmappings
   * @request GET:/timetables/{timetableId}/lessonmappings
   * @deprecated
   * @secure
   */
  searchLessonmappings = (timetableId: string, params: RequestParams = {}) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lessonmappings`,
      method: "GET",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name GetLessonChangesLessonchanges
   * @request GET:/timetables/{timetableId}/lesson-changes
   * @secure
   */
  getLessonChangesLessonchanges = (
    timetableId: string,
    query: {
      changeType: "LESSON" | "SCHEDULE";
      lessonChangeTypes?: (
        | "EXCHANGE"
        | "ADJUSTMENT"
        | "REPLACEMENT"
        | "ADDITION"
        | "COMBINATION"
        | "MULTIPLE"
        | "EVENT"
        | "REASSIGNMENT"
        | "DUPLICATION"
        | "REMOVAL"
        | "INTERNAL_SWAP"
        | "EXTERNAL_SWAP"
        | "NONE"
      )[];
      statuses?: (
        | "PENDING"
        | "COMPLETED"
        | "CANCELED"
        | "REJECTED"
        | "IGNORED"
        | "RECOVERED"
      )[];
      /** @format int64 */
      startTimestamp?: number;
      /** @format int64 */
      endTimestamp?: number;
      keyword?: string;
      /** @format uuid */
      classId?: string;
      /** @format uuid */
      teacherId?: string;
      /** @format int32 */
      lessonDateStart?: number;
      /** @format int32 */
      lessonDateEnd?: number;
      pageable: Pageable;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name GetRequestedLessonChangesCountPending
   * @request GET:/timetables/{timetableId}/lesson-changes/pending
   * @secure
   */
  getRequestedLessonChangesCountPending = (
    timetableId: string,
    query: {
      changeType: "LESSON" | "SCHEDULE";
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/pending`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name GetMyLessonChangesRequestsMyrequests
   * @request GET:/timetables/{timetableId}/lesson-changes/my-requests
   * @secure
   */
  getMyLessonChangesRequestsMyrequests = (
    timetableId: string,
    query: {
      changeType: "LESSON" | "SCHEDULE";
      lessonChangeTypes?: (
        | "EXCHANGE"
        | "ADJUSTMENT"
        | "REPLACEMENT"
        | "ADDITION"
        | "COMBINATION"
        | "MULTIPLE"
        | "EVENT"
        | "REASSIGNMENT"
        | "DUPLICATION"
        | "REMOVAL"
        | "INTERNAL_SWAP"
        | "EXTERNAL_SWAP"
        | "NONE"
      )[];
      statuses?: (
        | "PENDING"
        | "COMPLETED"
        | "CANCELED"
        | "REJECTED"
        | "IGNORED"
        | "RECOVERED"
      )[];
      /** @format int64 */
      startTimestamp?: number;
      /** @format int64 */
      endTimestamp?: number;
      keyword?: string;
      pageable: Pageable;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/my-requests`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name SearchTeacherOptionsForCombinationCombinationoptions
   * @request GET:/timetables/{timetableId}/lesson-changes/combination-options
   * @secure
   */
  searchTeacherOptionsForCombinationCombinationoptions = (
    timetableId: string,
    query: {
      /** @format uuid */
      dailyLessonId: string;
      /** @format int32 */
      lessonDate: number;
      /** @format int32 */
      period: number;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/combination-options`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name GetTeacherOptionsForAdjustmentCountbyteachers
   * @request GET:/timetables/{timetableId}/lesson-changes/adjustments/count-by-teachers
   * @secure
   */
  getTeacherOptionsForAdjustmentCountbyteachers = (
    timetableId: string,
    query: {
      /** @format int32 */
      lessonDate: number;
      /** @format int32 */
      period: number;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-changes/adjustments/count-by-teachers`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00. 전체 시간표 수업 변경
   * @name GetLessonChangeDetailsLessonchangedetailsLessonChangeId
   * @request GET:/timetables/{timetableId}/lesson-change-details/{lessonChangeId}
   * @secure
   */
  getLessonChangeDetailsLessonchangedetailsLessonChangeId = (
    timetableId: string,
    lessonChangeId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-change-details/${lessonChangeId}`,
      method: "GET",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 00-1. 전체 시간표 수업 정보
   * @name GetTimetableDailyLessonsBetweenDatesStartDateEndDate
   * @request GET:/timetables/{timetableId}/daily-lessons/{startDate}/{endDate}
   * @secure
   */
  getTimetableDailyLessonsBetweenDatesStartDateEndDate = (
    timetableId: string,
    startDate: number,
    endDate: number,
    query?: {
      /** @format uuid */
      teacherId?: string;
      /** @format uuid */
      classId?: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/daily-lessons/${startDate}/${endDate}`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 05. 시간표 과목 관리
   * @name FindAllSimpleSimple
   * @request GET:/timetables/{timetableId}/courses/simple
   * @secure
   */
  findAllSimpleSimple = (timetableId: string, params: RequestParams = {}) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/courses/simple`,
      method: "GET",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-class-controller
   * @name GetTimetableClassesClasses
   * @request GET:/timetables/{timetableId}/classes
   * @secure
   */
  getTimetableClassesClasses = (
    timetableId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/classes`,
      method: "GET",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name GetBasicInfoBasicinfo
   * @request GET:/timetables/{timetableId}/basicinfo
   * @secure
   */
  getBasicInfoBasicinfo = (timetableId: string, params: RequestParams = {}) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/basicinfo`,
      method: "GET",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-basic-template-controller
   * @name GetTimetableBasicTemplatesBasictemplates
   * @request GET:/timetables/{timetableId}/basic-templates
   * @secure
   */
  getTimetableBasicTemplatesBasictemplates = (
    timetableId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/basic-templates`,
      method: "GET",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 02. 시간표 교사 정보
   * @name GetEletterTeachersAvailableteachers
   * @request GET:/timetables/{timetableId}/available-teachers
   * @secure
   */
  getEletterTeachersAvailableteachers = (
    timetableId: string,
    query: {
      /** @format uuid */
      schoolId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/available-teachers`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name GetTimetableApplyDateApplydate
   * @request GET:/timetables/{timetableId}/apply-date
   * @secure
   */
  getTimetableApplyDateApplydate = (
    timetableId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/apply-date`,
      method: "GET",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-standard-course-controller
   * @name GetStandardCoursesStandardcourses
   * @request GET:/timetables/standard-courses
   * @secure
   */
  getStandardCoursesStandardcourses = (
    query: {
      keyword: string;
      /** @format uuid */
      timetableId?: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/standard-courses`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-school-controller
   * @name GetSchoolTimetableUsageStatusesBySchoolIdUsagestatus
   * @request GET:/timetables/schools/{schoolId}/usage-status
   * @secure
   */
  getSchoolTimetableUsageStatusesBySchoolIdUsagestatus = (
    schoolId: string,
    query?: {
      /** @format int32 */
      date?: number;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/schools/${schoolId}/usage-status`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-school-controller
   * @name GetSchoolActiveTimetableTeachersTeachers
   * @request GET:/timetables/schools/{schoolId}/teachers
   * @secure
   */
  getSchoolActiveTimetableTeachersTeachers = (
    schoolId: string,
    query?: {
      /** @format int32 */
      date?: number;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/schools/${schoolId}/teachers`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-school-controller
   * @name GetSchoolTimetableTeachersTeachersTeacherId
   * @request GET:/timetables/schools/{schoolId}/teachers/{teacherId}
   * @secure
   */
  getSchoolTimetableTeachersTeachersTeacherId = (
    schoolId: string,
    teacherId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/schools/${schoolId}/teachers/${teacherId}`,
      method: "GET",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-school-controller
   * @name GetSchoolActiveTimetableTeacherCoursesTeachercourses
   * @request GET:/timetables/schools/{schoolId}/teacher-courses
   * @secure
   */
  getSchoolActiveTimetableTeacherCoursesTeachercourses = (
    schoolId: string,
    query?: {
      /** @format int32 */
      date?: number;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/schools/${schoolId}/teacher-courses`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name GetTimetableSchoolRoleRole
   * @request GET:/timetables/schools/{schoolId}/role
   * @secure
   */
  getTimetableSchoolRoleRole = (schoolId: string, params: RequestParams = {}) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/schools/${schoolId}/role`,
      method: "GET",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-school-controller
   * @name GetSchoolActiveTimetableConfigConfig
   * @request GET:/timetables/schools/{schoolId}/config
   * @secure
   */
  getSchoolActiveTimetableConfigConfig = (
    schoolId: string,
    query?: {
      /** @format int32 */
      date?: number;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/schools/${schoolId}/config`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-school-controller
   * @name GetSchoolActiveTimetableClassesClasses
   * @request GET:/timetables/schools/{schoolId}/classes
   * @secure
   */
  getSchoolActiveTimetableClassesClasses = (
    schoolId: string,
    query?: {
      /** @format int32 */
      date?: number;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/schools/${schoolId}/classes`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-school-controller
   * @name GetSchoolTimetableUsageStatusesUsagestatuses
   * @request GET:/timetables/schools/usage-statuses
   * @secure
   */
  getSchoolTimetableUsageStatusesUsagestatuses = (
    query?: {
      /** @format int32 */
      date?: number;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/schools/usage-statuses`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-school-controller
   * @name GetRequestedLessonChangesCountOfSchoolPending
   * @request GET:/timetables/schooles/{schoolId}/lesson-changes/pending
   * @secure
   */
  getRequestedLessonChangesCountOfSchoolPending = (
    schoolId: string,
    query: {
      changeType: "LESSON" | "SCHEDULE";
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/schooles/${schoolId}/lesson-changes/pending`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name CheckTimetableNameDuplicate
   * @request GET:/timetables/duplicate
   * @secure
   */
  checkTimetableNameDuplicate = (
    query: {
      timetableName: string;
      /** @format uuid */
      schoolId: string;
      /** @format uuid */
      timetableId?: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/duplicate`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 01. 기초 시간표 관리
   * @name GetActiveTimetableByDateActivebydateDate
   * @request GET:/timetables/active-by-date/{date}
   * @secure
   */
  getActiveTimetableByDateActivebydateDate = (
    date: number,
    query: {
      /** @format uuid */
      schoolId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/active-by-date/${date}`,
      method: "GET",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-specialty-room-controller
   * @name DeleteSpecialtyRoomSpecialtyroomsSpecialtyRoomId
   * @request DELETE:/timetables/{timetableId}/specialty-rooms/{specialtyRoomId}
   * @secure
   */
  deleteSpecialtyRoomSpecialtyroomsSpecialtyRoomId = (
    timetableId: string,
    specialtyRoomId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/specialty-rooms/${specialtyRoomId}`,
      method: "DELETE",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 03. 시간표 기준 과목 정보
   * @name DetachSimilarCourseCoursebasesCourseBaseId
   * @request DELETE:/timetables/{timetableId}/similar-course-confs/{similarCourseConfId}/course-bases/{courseBaseId}
   * @secure
   */
  detachSimilarCourseCoursebasesCourseBaseId = (
    timetableId: string,
    similarCourseConfId: string,
    courseBaseId: string,
    query: {
      /** @format uuid */
      templateId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/similar-course-confs/${similarCourseConfId}/course-bases/${courseBaseId}`,
      method: "DELETE",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags 04. 시수표 정보 관리
   * @name DeleteLessonConfLessonconfsLessonConfId
   * @request DELETE:/timetables/{timetableId}/lesson-confs/{lessonConfId}
   * @secure
   */
  deleteLessonConfLessonconfsLessonConfId = (
    timetableId: string,
    lessonConfId: string,
    query: {
      /** @format uuid */
      templateId: string;
    },
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/lesson-confs/${lessonConfId}`,
      method: "DELETE",
      query: query,
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-fixed-conf-controller
   * @name DeleteFixedConfFixedconfsFixedConfId
   * @request DELETE:/timetables/{timetableId}/fixed-confs/{fixedConfId}
   * @secure
   */
  deleteFixedConfFixedconfsFixedConfId = (
    timetableId: string,
    fixedConfId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/fixed-confs/${fixedConfId}`,
      method: "DELETE",
      secure: true,
      format: "json",
      ...params,
    });
  /**
   * No description
   *
   * @tags timetable-basic-template-controller
   * @name DeleteTimetableBasicTemplateLessonLessonsLessonId
   * @request DELETE:/timetables/{timetableId}/basic-template/lessons/{lessonId}
   * @secure
   */
  deleteTimetableBasicTemplateLessonLessonsLessonId = (
    timetableId: string,
    lessonId: string,
    params: RequestParams = {},
  ) =>
    this.request<TimetableUpdateStatusDto, any>({
      path: `/timetables/${timetableId}/basic-template/lessons/${lessonId}`,
      method: "DELETE",
      secure: true,
      format: "json",
      ...params,
    });
}
